### ISSUE TITLE
The function or variable 'center' is not recognized.

### ISSUE THREAD

**Issue by yqw0710** [nick-jhlee/fair-manifold-pca#1]
Hello,I have a question here.When I run synthetic1.m,it shows "The function or variable 'center' is not recognized." in the mbfpca function. I didn't find the center function in the project.

**Comment by nick-jhlee** [comment]
Hi, sorry for the late reply.
In the latest commit, this error has been fixed, and thus I'll close this issue.

**Comment by nick-jhlee** [comment]
Hi, sorry for the late reply.
In the latest commit, this error has been fixed, and thus I'll close this issue.
